const MovieData = [
    {
        id: 1,
        title: 'The Avenger',
        release: 2012,
        from: 'America',
        img: 'images/ott/temporary1.png',
        genre: 'mystery/horror',
        duration: '8h 00m',
        rating: '8.0',
        description: 'A group of heroes unite to fight an unseen enemy.',
    },
    {
        id: 2,
        title: 'Lost in Time',
        release: 2015,
        from: 'UK',
        img: 'images/ott/temporary2.png',
        genre: 'sci-fi/drama',
        duration: '2h 15m',
        rating: '7.5',
        description: 'A scientist discovers a portal to the past with dangerous consequences.',
    },
    {
        id: 3,
        title: 'Silent Whisper',
        release: 2018,
        from: 'Canada',
        img: 'images/ott/temporary3.png',
        genre: 'thriller',
        duration: '1h 45m',
        rating: '7.8',
        description: 'A detective hunts a mysterious serial killer in the city.',
    },
    {
        id: 4,
        title: 'Ocean’s Secret',
        release: 2020,
        from: 'Australia',
        img: 'images/ott/temporary4.png',
        genre: 'adventure',
        duration: '2h 05m',
        rating: '8.2',
        description: 'An explorer searches for a lost treasure beneath the sea.',
    },
    {
        id: 5,
        title: 'Neon Dreams',
        release: 2019,
        from: 'Japan',
        img: 'images/ott/temporary5.png',
        genre: 'cyberpunk',
        duration: '1h 50m',
        rating: '7.9',
        description: 'In a futuristic city, a hacker fights against a corrupt corporation.',
    },
    {
        id: 6,
        title: 'Midnight Melody',
        release: 2017,
        from: 'France',
        img: 'images/ott/temporary6.png',
        genre: 'romance/drama',
        duration: '2h 10m',
        rating: '7.4',
        description: 'Two musicians find love through their shared passion for music.',
    },
    {
        id: 7,
        title: 'Ghost of the Valley',
        release: 2021,
        from: 'South Korea',
        img: 'images/ott/temporary7.png',
        genre: 'horror',
        duration: '1h 40m',
        rating: '6.9',
        description: 'A haunted village hides dark secrets from its past.',
    },
    {
        id: 8,
        title: 'Steel Horizon',
        release: 2016,
        from: 'Germany',
        img: 'images/ott/temporary8.png',
        genre: 'action',
        duration: '2h 20m',
        rating: '7.7',
        description: 'A soldier fights to protect his country during an intense war.',
    },
    {
        id: 9,
        title: 'The Last Garden',
        release: 2014,
        from: 'Italy',
        img: 'images/ott/temporary9.png',
        genre: 'fantasy',
        duration: '1h 55m',
        rating: '8.1',
        description: 'A magical garden holds the key to eternal youth.',
    },
    {
        id: 10,
        title: 'City of Shadows',
        release: 2013,
        from: 'Mexico',
        img: 'images/ott/temporary10.png',
        genre: 'crime/drama',
        duration: '2h 00m',
        rating: '7.3',
        description: 'A detective uncovers corruption in a city ruled by gangs.',
    },
    {
        id: 11,
        title: 'Frozen Echo',
        release: 2019,
        from: 'Russia',
        img: 'images/ott/temporary11.png',
        genre: 'thriller/mystery',
        duration: '1h 50m',
        rating: '7.6',
        description: 'A remote town experiences strange phenomena during the winter.',
    },
    {
        id: 12,
        title: 'Beyond the Stars',
        release: 2018,
        from: 'USA',
        img: 'images/ott/temporary12.png',
        genre: 'sci-fi/adventure',
        duration: '2h 30m',
        rating: '8.4',
        description: 'Astronauts embark on a mission to explore distant galaxies.',
    },
    {
        id: 13,
        title: 'The Painter’s Secret',
        release: 2017,
        from: 'Spain',
        img: 'images/ott/temporary13.png',
        genre: 'drama',
        duration: '1h 45m',
        rating: '7.2',
        description: 'An artist reveals the mystery behind his masterpiece.',
    },
    {
        id: 14,
        title: 'Desert Mirage',
        release: 2020,
        from: 'Egypt',
        img: 'images/ott/temporary14.png',
        genre: 'adventure',
        duration: '2h 10m',
        rating: '7.8',
        description: 'A treasure hunter ventures deep into the desert for a hidden artifact.',
    },
    {
        id: 15,
        title: 'Whispering Winds',
        release: 2016,
        from: 'New Zealand',
        img: 'images/ott/temporary15.png',
        genre: 'fantasy/romance',
        duration: '1h 50m',
        rating: '7.5',
        description: 'A magical journey where love conquers all obstacles.',
    },
    {
        id: 16,
        title: 'Ironclad',
        release: 2015,
        from: 'UK',
        img: 'images/ott/temporary16.png',
        genre: 'historical/action',
        duration: '2h 00m',
        rating: '7.9',
        description: 'Knights defend their kingdom during a brutal siege.',
    },
    {
        id: 17,
        title: 'Crystal Lake',
        release: 2018,
        from: 'Canada',
        img: 'images/ott/temporary17.png',
        genre: 'horror/thriller',
        duration: '1h 40m',
        rating: '6.8',
        description: 'Strange happenings at a secluded lake cabin.',
    },
    {
        id: 18,
        title: 'Sunset Boulevard',
        release: 2014,
        from: 'USA',
        img: 'images/ott/temporary18.png',
        genre: 'drama',
        duration: '2h 05m',
        rating: '7.1',
        description: 'The rise and fall of a Hollywood star.',
    },
    {
        id: 19,
        title: 'Quantum Rift',
        release: 2021,
        from: 'Germany',
        img: 'images/ott/temporary19.png',
        genre: 'sci-fi/thriller',
        duration: '2h 15m',
        rating: '8.3',
        description: 'Scientists race to stop a catastrophic dimensional collapse.',
    },
    {
        id: 20,
        title: 'The Forgotten Realm',
        release: 2013,
        from: 'France',
        img: 'images/ott/temporary20.png',
        genre: 'fantasy/adventure',
        duration: '2h 25m',
        rating: '7.7',
        description: 'Adventurers discover a lost kingdom hidden by magic.',
    },
];

export default MovieData;
