const NowPlayingData = {
    dates: {
        maximum: '2025-09-17',
        minimum: '2025-08-06',
    },
    page: 1,
    results: [
        {
            adult: false,
            backdrop_path: '/fq8gLtrz1ByW3KQ2IM3RMZEIjsQ.jpg',
            genre_ids: [27],
            id: 1038392,
            original_language: 'en',
            original_title: 'The Conjuring: Last Rites',
            overview:
                'Paranormal investigators Ed and Lorraine Warren take on one last terrifying case involving mysterious entities they must confront.',
            popularity: 546.684,
            poster_path: '/uDXlaT45ptoW3RAEYTWXeUlenhA.jpg',
            release_date: '2025-09-03',
            title: 'The Conjuring: Last Rites',
            video: false,
            vote_average: 6.97,
            vote_count: 182,
        },
        {
            adult: false,
            backdrop_path: '/mEW9XMgYDO6U0MJcIRqRuSwjzN5.jpg',
            genre_ids: [28, 53],
            id: 1007734,
            original_language: 'en',
            original_title: 'Nobody 2',
            overview:
                'Former assassin Hutch Mansell takes his family on a nostalgic vacation to a small-town theme park, only to be pulled back into violence when they clash with a corrupt operator, a crooked sheriff, and a ruthless crime boss.',
            popularity: 412.3794,
            poster_path: '/svXVRoRSu6zzFtCzkRsjZS7Lqpd.jpg',
            release_date: '2025-08-13',
            title: 'Nobody 2',
            video: false,
            vote_average: 7.239,
            vote_count: 394,
        },
        {
            adult: false,
            backdrop_path: '/wJ20rOZ1VgkCqv1jeOQB2Brny9k.jpg',
            genre_ids: [27, 9648],
            id: 1078605,
            original_language: 'en',
            original_title: 'Weapons',
            overview:
                'When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.',
            popularity: 414.2818,
            poster_path: '/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg',
            release_date: '2025-08-04',
            title: 'Weapons',
            video: false,
            vote_average: 7.5,
            vote_count: 963,
        },
        {
            adult: false,
            backdrop_path: '/1wi1hcbl6KYqARjdQ4qrBWZdiau.jpg',
            genre_ids: [28, 35, 80],
            id: 1035259,
            original_language: 'en',
            original_title: 'The Naked Gun',
            overview:
                'Only one man has the particular set of skills... to lead Police Squad and save the world: Lt. Frank Drebin Jr.',
            popularity: 341.7315,
            poster_path: '/aq0JMbmSfPwG8JvAzExJPrBHqmG.jpg',
            release_date: '2025-07-30',
            title: 'The Naked Gun',
            video: false,
            vote_average: 6.772,
            vote_count: 553,
        },
        {
            adult: false,
            backdrop_path: '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
            genre_ids: [16, 28, 14, 53],
            id: 1311031,
            original_language: 'ja',
            original_title: '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
            overview:
                'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
            popularity: 295.0934,
            poster_path: '/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg',
            release_date: '2025-07-18',
            title: 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
            video: false,
            vote_average: 7.352,
            vote_count: 105,
        },
        {
            adult: false,
            backdrop_path: '/zNriRTr0kWwyaXPzdg1EIxf0BWk.jpg',
            genre_ids: [878, 12, 28],
            id: 1234821,
            original_language: 'en',
            original_title: 'Jurassic World Rebirth',
            overview:
                "Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
            popularity: 206.1198,
            poster_path: '/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg',
            release_date: '2025-07-01',
            title: 'Jurassic World Rebirth',
            video: false,
            vote_average: 6.4,
            vote_count: 2029,
        },
        {
            adult: false,
            backdrop_path: '/dg1VXTXSChZG3O5c1Op5kozbi2q.jpg',
            genre_ids: [53, 80, 18],
            id: 1242434,
            original_language: 'en',
            original_title: 'Highest 2 Lowest',
            overview:
                'When a titan music mogul, widely known as having the "best ears in the business", is targeted with a ransom plot, he is jammed up in a life-or-death moral dilemma.',
            popularity: 188.3262,
            poster_path: '/kOzwIr0R7WhaFgoYUZFLPZA2RBZ.jpg',
            release_date: '2025-08-14',
            title: 'Highest 2 Lowest',
            video: false,
            vote_average: 5.878,
            vote_count: 164,
        },
        {
            adult: false,
            backdrop_path: '/2nwhxEyefcIFKwOrSigiamoIzu2.jpg',
            genre_ids: [28, 53, 18],
            id: 1119878,
            original_language: 'en',
            original_title: 'Ice Road: Vengeance',
            overview:
                'Big rig ice road driver Mike McCann travels to Nepal to scatter his late brother’s ashes on Mt. Everest. While on a packed tour bus traversing the deadly 12,000 ft. terrain of the infamous Road to the Sky, McCann and his mountain guide encounter a group of mercenaries and must fight to save themselves, the busload of innocent travelers, and the local villagers’ homeland.',
            popularity: 174.8746,
            poster_path: '/cQN9rZj06rXMVkk76UF1DfBAico.jpg',
            release_date: '2025-06-27',
            title: 'Ice Road: Vengeance',
            video: false,
            vote_average: 6.599,
            vote_count: 307,
        },
        {
            adult: false,
            backdrop_path: '/uBB1aMga5ngZxsUQL5k36zeW3pB.jpg',
            genre_ids: [27, 10749],
            id: 1242011,
            original_language: 'en',
            original_title: 'Together',
            overview:
                "With a move to the countryside already testing the limits of a couple's relationship, a supernatural encounter begins an extreme transformation of their love, their lives, and their flesh.",
            popularity: 164.3621,
            poster_path: '/m52XidzKx94bKlToZfEXUnL3pdy.jpg',
            release_date: '2025-07-23',
            title: 'Together',
            video: false,
            vote_average: 7.2,
            vote_count: 385,
        },
        {
            adult: false,
            backdrop_path: '/w3Bi0wygeFQctn6AqFTwhGNXRwL.jpg',
            genre_ids: [16, 35, 14, 10402],
            id: 803796,
            original_language: 'en',
            original_title: 'KPop Demon Hunters',
            overview:
                "When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.",
            popularity: 156.2718,
            poster_path: '/22AouvwlhlXbe3nrFcjzL24bvWH.jpg',
            release_date: '2025-06-20',
            title: 'KPop Demon Hunters',
            video: false,
            vote_average: 8.35,
            vote_count: 1322,
        },
        {
            adult: false,
            backdrop_path: '/yth78N88nwokepnOe5atwPGfTL1.jpg',
            genre_ids: [28, 80, 53],
            id: 1382406,
            original_language: 'zh',
            original_title: '惊天大营救',
            overview:
                'A veteran Muay Thai expert goes on a take-no-prisoners mission of revenge after his wife and daughter are brutally murdered by mysterious forces.',
            popularity: 143.5146,
            poster_path: '/nML8rOI4GOiiEsXgknuhZeUF8M7.jpg',
            release_date: '2024-12-05',
            title: 'Striking Rescue',
            video: false,
            vote_average: 7.584,
            vote_count: 107,
        },
        {
            adult: false,
            backdrop_path: '/8J6UlIFcU7eZfq9iCLbgc8Auklg.jpg',
            genre_ids: [14, 10751, 28, 12],
            id: 1087192,
            original_language: 'en',
            original_title: 'How to Train Your Dragon',
            overview:
                'On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.',
            popularity: 159.7382,
            poster_path: '/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg',
            release_date: '2025-06-06',
            title: 'How to Train Your Dragon',
            video: false,
            vote_average: 8,
            vote_count: 1854,
        },
        {
            adult: false,
            backdrop_path: '/xSD0q1FiuZkvHuy7uscOLbmd1hR.jpg',
            genre_ids: [12, 28, 14],
            id: 13494,
            original_language: 'en',
            original_title: 'Red Sonja',
            overview:
                'A young girl rises from the ashes of tragedy to become the most feared warrior woman of all time: the She-Devil with a Sword.',
            popularity: 146.5014,
            poster_path: '/l10eghFN1nQmWwMSt91MlLvZZFA.jpg',
            release_date: '2025-07-31',
            title: 'Red Sonja',
            video: false,
            vote_average: 5.8,
            vote_count: 71,
        },
        {
            adult: false,
            backdrop_path: '/8jeDyvFQKgss36FbGAmGQVzPXlH.jpg',
            genre_ids: [53, 28, 35],
            id: 1151334,
            original_language: 'en',
            original_title: 'Eenie Meanie',
            overview:
                'A former teenage getaway driver gets dragged back into her unsavory past when a former employer offers her a chance to save the life of her chronically unreliable ex-boyfriend.',
            popularity: 135.8592,
            poster_path: '/12Va3oO3oYUdOd75zM57Nx1976a.jpg',
            release_date: '2025-08-21',
            title: 'Eenie Meanie',
            video: false,
            vote_average: 6.415,
            vote_count: 170,
        },
        {
            adult: false,
            backdrop_path: '/jvpkBenB6hv19WWYVlaiow8zklq.jpg',
            genre_ids: [16, 10751, 35, 80, 12],
            id: 1175942,
            original_language: 'en',
            original_title: 'The Bad Guys 2',
            overview:
                'The now-reformed Bad Guys are trying (very, very hard) to be good, but instead find themselves hijacked into a high-stakes, globe-trotting heist, masterminded by a new team of criminals they never saw coming: The Bad Girls.',
            popularity: 135.6637,
            poster_path: '/26oSPnq0ct59l07QOXZKyzsiRtN.jpg',
            release_date: '2025-07-24',
            title: 'The Bad Guys 2',
            video: false,
            vote_average: 7.8,
            vote_count: 332,
        },
        {
            adult: false,
            backdrop_path: '/7U6sslMcPXPs9MIH5IvAl8ttTth.jpg',
            genre_ids: [53, 878, 27],
            id: 1530127,
            original_language: 'en',
            original_title: 'Lookout',
            overview:
                'Seeking peace away from her turbulent life, a young woman accepts a job as a fire lookout at a remote wilderness tower. As she settles into her new role, eerie disturbances and strange occurrences begin to unfold, and she must uncover the chilling secrets that disrupt her isolation before it’s too late.',
            popularity: 137.1326,
            poster_path: '/nlMsTk94ylLywUdDWsOqwBDi19l.jpg',
            release_date: '2025-09-02',
            title: 'Lookout',
            video: false,
            vote_average: 8.7,
            vote_count: 3,
        },
        {
            adult: false,
            backdrop_path: '/dcLV5rEXuQRW0ZlB7IMLArHMyWh.jpg',
            genre_ids: [35, 14, 10751],
            id: 1125257,
            original_language: 'en',
            original_title: 'Freakier Friday',
            overview:
                'Years after Tess and Anna endured an identity crisis, Anna now has a daughter of her own and a soon-to-be stepdaughter. As they navigate the myriad challenges that come when two families merge, Tess and Anna discover lightning might indeed strike twice.',
            popularity: 105.9453,
            poster_path: '/9wV65OmsjLAqBfDnYTkMPutXH8j.jpg',
            release_date: '2025-08-06',
            title: 'Freakier Friday',
            video: false,
            vote_average: 6.9,
            vote_count: 163,
        },
        {
            adult: false,
            backdrop_path: '/fMlAg1CyHTsCktwQrp74rl9RMwJ.jpg',
            genre_ids: [27, 53],
            id: 138843,
            original_language: 'en',
            original_title: 'The Conjuring',
            overview:
                'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse. Forced to confront a powerful entity, the Warrens find themselves caught in the most terrifying case of their lives.',
            popularity: 105.8174,
            poster_path: '/wVYREutTvI2tmxr6ujrHT704wGF.jpg',
            release_date: '2013-07-18',
            title: 'The Conjuring',
            video: false,
            vote_average: 7.54,
            vote_count: 12120,
        },
        {
            adult: false,
            backdrop_path: '/sItIskd5xpiE64bBWYwZintkGf3.jpg',
            genre_ids: [28, 53, 80],
            id: 541671,
            original_language: 'en',
            original_title: 'Ballerina',
            overview:
                'Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.',
            popularity: 101.4819,
            poster_path: '/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg',
            release_date: '2025-06-04',
            title: 'Ballerina',
            video: false,
            vote_average: 7.394,
            vote_count: 1564,
        },
        {
            adult: false,
            backdrop_path: '/mOcMPfCJEvSREq8OZzg42gFgrGt.jpg',
            genre_ids: [10749, 53],
            id: 1300116,
            original_language: 'de',
            original_title: 'Fall for Me',
            overview:
                "Lilli is suspicious of her sister's new fiance, but when an attractive stranger enters her life, she's suddenly distracted by the thralls of desire.",
            popularity: 80.2402,
            poster_path: '/nLTs9SNBuk3DuB8D0p3mSsPYN7J.jpg',
            release_date: '2025-08-20',
            title: 'Fall for Me',
            video: false,
            vote_average: 6.14,
            vote_count: 100,
        },
    ],
    total_pages: 231,
    total_results: 4612,
};

export default NowPlayingData;
