const UpcomingData = {
    dates: {
        maximum: '2025-10-08',
        minimum: '2025-09-17',
    },
    page: 1,
    results: [
        {
            adult: false,
            backdrop_path: '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
            genre_ids: [16, 28, 14, 53],
            id: 1311031,
            original_language: 'ja',
            original_title: '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
            overview:
                'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
            popularity: 295.0934,
            poster_path: '/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg',
            release_date: '2025-07-18',
            title: 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
            video: false,
            vote_average: 7.4,
            vote_count: 105,
        },
        {
            adult: false,
            backdrop_path: '/uBB1aMga5ngZxsUQL5k36zeW3pB.jpg',
            genre_ids: [27, 10749],
            id: 1242011,
            original_language: 'en',
            original_title: 'Together',
            overview:
                "With a move to the countryside already testing the limits of a couple's relationship, a supernatural encounter begins an extreme transformation of their love, their lives, and their flesh.",
            popularity: 164.3621,
            poster_path: '/m52XidzKx94bKlToZfEXUnL3pdy.jpg',
            release_date: '2025-07-23',
            title: 'Together',
            video: false,
            vote_average: 7.159,
            vote_count: 387,
        },
        {
            adult: false,
            backdrop_path: '/jvpkBenB6hv19WWYVlaiow8zklq.jpg',
            genre_ids: [16, 10751, 35, 80, 12],
            id: 1175942,
            original_language: 'en',
            original_title: 'The Bad Guys 2',
            overview:
                'The now-reformed Bad Guys are trying (very, very hard) to be good, but instead find themselves hijacked into a high-stakes, globe-trotting heist, masterminded by a new team of criminals they never saw coming: The Bad Girls.',
            popularity: 135.6637,
            poster_path: '/26oSPnq0ct59l07QOXZKyzsiRtN.jpg',
            release_date: '2025-07-24',
            title: 'The Bad Guys 2',
            video: false,
            vote_average: 7.832,
            vote_count: 333,
        },
        {
            adult: false,
            backdrop_path: '/zxi6WQPVc0uQAG5TtLsKvxYHApC.jpg',
            genre_ids: [16, 14, 12, 28],
            id: 980477,
            original_language: 'zh',
            original_title: '哪吒之魔童闹海',
            overview:
                'After a catastrophic event leaves their bodies destroyed, Ne Zha and Ao Bing are granted a fragile second chance at life. As tensions rise between the dragon clans and celestial forces, the two must undergo a series of perilous trials that will test their bond, challenge their identities, and decide the fate of both mortals and immortals.',
            popularity: 73.0283,
            poster_path: '/cb5NyNrqiCNNoDkA8FfxHAtypdG.jpg',
            release_date: '2025-01-29',
            title: 'Ne Zha 2',
            video: false,
            vote_average: 8,
            vote_count: 350,
        },
        {
            adult: false,
            backdrop_path: '/cjhq1eBLXgKq1xHDFeUnYzu61H6.jpg',
            genre_ids: [35, 80],
            id: 1149504,
            original_language: 'en',
            original_title: "Honey Don't!",
            overview:
                "Honey O'Donahue, a small-town private investigator, delves into a series of strange deaths tied to a mysterious church.",
            popularity: 87.8663,
            poster_path: '/fJm3kmd9NLZWypMas7g34oNFgbk.jpg',
            release_date: '2025-08-21',
            title: "Honey Don't!",
            video: false,
            vote_average: 5.809,
            vote_count: 47,
        },
        {
            adult: false,
            backdrop_path: '/4BtL2vvEufDXDP4u6xQjjQ1Y2aT.jpg',
            genre_ids: [28, 80, 53],
            id: 1419406,
            original_language: 'zh',
            original_title: '捕风追影',
            overview:
                'Macau Police brings the tracking expert police officer out of retirement to help catch a dangerous group of professional thieves.',
            popularity: 57.4324,
            poster_path: '/e0RU6KpdnrqFxDKlI3NOqN8nHL6.jpg',
            release_date: '2025-08-16',
            title: "The Shadow's Edge",
            video: false,
            vote_average: 7.5,
            vote_count: 20,
        },
        {
            adult: false,
            backdrop_path: '/9whEVuKte4Qi0LI4TzPf7glinJW.jpg',
            genre_ids: [16, 10751, 14],
            id: 936108,
            original_language: 'en',
            original_title: 'Smurfs',
            overview:
                'When Papa Smurf is mysteriously taken by evil wizards, Razamel and Gargamel, Smurfette leads the Smurfs on a mission into the real world to save him. With the help of new friends, the Smurfs must discover what defines their destiny to save the universe.',
            popularity: 43.9013,
            poster_path: '/8o6lkhL32xQJeB52IIG1us5BVey.jpg',
            release_date: '2025-07-05',
            title: 'Smurfs',
            video: false,
            vote_average: 6,
            vote_count: 169,
        },
        {
            adult: false,
            backdrop_path: '/fTrQsdMS2MUw00RnzH0r3JWHhts.jpg',
            genre_ids: [28, 80, 53],
            id: 1197306,
            original_language: 'en',
            original_title: 'A Working Man',
            overview:
                "Levon Cade left behind a decorated military career in the black ops to live a simple life working construction. But when his boss's daughter, who is like family to him, is taken by human traffickers, his search to bring her home uncovers a world of corruption far greater than he ever could have imagined.",
            popularity: 39.8069,
            poster_path: '/6FRFIogh3zFnVWn7Z6zcYnIbRcX.jpg',
            release_date: '2025-03-26',
            title: 'A Working Man',
            video: false,
            vote_average: 6.7,
            vote_count: 1537,
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [18],
            id: 1091043,
            original_language: 'ta',
            original_title: 'தண்டகாரண்யம்',
            overview: 'A young man’s struggles to secure a government job.',
            popularity: 36.9496,
            poster_path: '/enkPbejfPmM8o2bgbhnLSX4fCAV.jpg',
            release_date: '2025-09-19',
            title: 'Thandakaaranyam',
            video: false,
            vote_average: 0,
            vote_count: 0,
        },
        {
            adult: false,
            backdrop_path: '/eNSUknQqzTXWE5EeT8ZnVccEPR0.jpg',
            genre_ids: [27, 53],
            id: 1285965,
            original_language: 'en',
            original_title: 'Dangerous Animals',
            overview:
                'A savvy and free-spirited surfer is abducted by a shark-obsessed serial killer. Held captive on his boat, she must figure out how to escape before he carries out a ritualistic feeding to the sharks below.',
            popularity: 30.1203,
            poster_path: '/oQJ1PKLIE2gF5cr3xwjLCvv4jcU.jpg',
            release_date: '2025-06-05',
            title: 'Dangerous Animals',
            video: false,
            vote_average: 6.5,
            vote_count: 244,
        },
        {
            adult: false,
            backdrop_path: '/eQV9rSQ6S1ja4lGTwHTnQuVhoG.jpg',
            genre_ids: [27, 35, 14, 18],
            id: 1284120,
            original_language: 'no',
            original_title: 'Den stygge stesøsteren',
            overview:
                'In a fairy-tale kingdom where beauty is a brutal business, Elvira battles to compete with her incredibly beautiful stepsister, and she will go to any length to catch the prince’s eye.',
            popularity: 29.2335,
            poster_path: '/crX9rSg9EohybhkEe8iTQUCe55y.jpg',
            release_date: '2025-03-07',
            title: 'The Ugly Stepsister',
            video: false,
            vote_average: 7.217,
            vote_count: 357,
        },
        {
            adult: false,
            backdrop_path: '/3htgvJ6d0GV633oHYueeISk8J7w.jpg',
            genre_ids: [12, 14, 35, 10751],
            id: 1319969,
            original_language: 'en',
            original_title: 'Sketch',
            overview:
                'When a young girl’s sketchbook falls into a strange pond, her drawings come to life—chaotic, real, and on the loose. As the town descends into chaos, her family must reunite and stop the monsters they never meant to unleash.',
            popularity: 27.5927,
            poster_path: '/sxiDj3dTgZuCPkx30Jvyq8K9QUV.jpg',
            release_date: '2025-08-06',
            title: 'Sketch',
            video: false,
            vote_average: 7.155,
            vote_count: 42,
        },
        {
            adult: false,
            backdrop_path: '/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg',
            genre_ids: [16, 12, 10751, 35],
            id: 862,
            original_language: 'en',
            original_title: 'Toy Story',
            overview:
                "Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.",
            popularity: 26.8541,
            poster_path: '/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg',
            release_date: '1995-11-22',
            title: 'Toy Story',
            video: false,
            vote_average: 7.97,
            vote_count: 19109,
        },
        {
            adult: false,
            backdrop_path: '/pcJft6lFWsJxutwpLHVYfmZRPQp.jpg',
            genre_ids: [27, 878],
            id: 604079,
            original_language: 'en',
            original_title: 'The Long Walk',
            overview:
                'In a dystopian, alternate-America ruled by a totalitarian regime, 50 teenage boys take part in a deadly annual walking contest, forced to maintain a minimum pace or be executed, until only one survivor remains.',
            popularity: 26.4535,
            poster_path: '/wobVTa99eW0ht6c1rNNzLkazPtR.jpg',
            release_date: '2025-09-10',
            title: 'The Long Walk',
            video: false,
            vote_average: 6.7,
            vote_count: 6,
        },
        {
            adult: false,
            backdrop_path: '/9ZhhlJbtLmzjvdbxbNzHZEBFdIZ.jpg',
            genre_ids: [80, 53, 35],
            id: 1245993,
            original_language: 'en',
            original_title: 'Caught Stealing',
            overview:
                'Burned-out ex-baseball player Hank Thompson unexpectedly finds himself embroiled in a dangerous struggle for survival amidst the criminal underbelly of 1990s New York City, forced to navigate a treacherous underworld he never imagined.',
            popularity: 22.3772,
            poster_path: '/cvda8s5J8YaHjTyEyXQpvD6f3iV.jpg',
            release_date: '2025-08-26',
            title: 'Caught Stealing',
            video: false,
            vote_average: 6.928,
            vote_count: 166,
        },
        {
            adult: false,
            backdrop_path: '/vcFs7lPVMOvYX7KMkDw66iUpoYp.jpg',
            genre_ids: [14, 18, 27],
            id: 1020822,
            original_language: 'fr',
            original_title: 'Animale',
            overview:
                'Camargue, France - Nejma trains hard to win the local bullfighting competition. When she is mauled after a celebration, she starts to notice disturbing changes. News of a rogue bull on the loose terrifies the community, killing young men.',
            popularity: 21.84,
            poster_path: '/htOG0XTgTLTSIraMvc468XZsUKP.jpg',
            release_date: '2024-09-20',
            title: 'Animale',
            video: false,
            vote_average: 6.95,
            vote_count: 20,
        },
        {
            adult: false,
            backdrop_path: '/qJzloL8O9YHhiWBrhlPfKAtZu2I.jpg',
            genre_ids: [28, 878],
            id: 557,
            original_language: 'en',
            original_title: 'Spider-Man',
            overview:
                'After being bitten by a genetically altered spider at Oscorp, nerdy but endearing high school student Peter Parker is endowed with amazing powers to become the superhero known as Spider-Man.',
            popularity: 21.2782,
            poster_path: '/gh4cZbhZxyTbgxQPxD0dOudNPTn.jpg',
            release_date: '2002-05-01',
            title: 'Spider-Man',
            video: false,
            vote_average: 7.316,
            vote_count: 19867,
        },
        {
            adult: false,
            backdrop_path: '/xgU3KkqiME9pGe5gGCNpUYkoSWg.jpg',
            genre_ids: [27, 53, 12],
            id: 578,
            original_language: 'en',
            original_title: 'Jaws',
            overview:
                "When the seaside community of Amity finds itself under attack by a dangerous great white shark, the town's chief of police, a young marine biologist, and a grizzled hunter embark on a desperate quest to destroy the beast before it strikes again.",
            popularity: 19.7506,
            poster_path: '/lxM6kqilAdpdhqUl2biYp5frUxE.jpg',
            release_date: '1975-06-20',
            title: 'Jaws',
            video: false,
            vote_average: 7.677,
            vote_count: 10989,
        },
        {
            adult: false,
            backdrop_path: '/8rpDcsfLJypbO6vREc0547VKqEv.jpg',
            genre_ids: [878, 12, 28],
            id: 76600,
            original_language: 'en',
            original_title: 'Avatar: The Way of Water',
            overview:
                'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
            popularity: 19.3642,
            poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
            release_date: '2022-12-14',
            title: 'Avatar: The Way of Water',
            video: false,
            vote_average: 7.6,
            vote_count: 12846,
        },
        {
            adult: false,
            backdrop_path: '/uWVkEo9PWHu9algZsiLPi6sRU64.jpg',
            genre_ids: [36, 18],
            id: 556574,
            original_language: 'en',
            original_title: 'Hamilton',
            overview:
                'Presenting the tale of American founding father Alexander Hamilton, this filmed version of the original Broadway smash hit is the story of America then, told by America now.',
            popularity: 18.2066,
            poster_path: '/h1B7tW0t399VDjAcWJh8m87469b.jpg',
            release_date: '2025-09-05',
            title: 'Hamilton',
            video: false,
            vote_average: 5.8,
            vote_count: 8,
        },
    ],
    total_pages: 65,
    total_results: 1290,
};

export default UpcomingData;
